### ISSUE TITLE
system image: include libqt5x11extras5 by default

### ISSUE THREAD

**Issue by krisjace** [ubports/ubuntu-touch-meta#33]
### Description of the feature
I would like for the default system image of ubports to include libqt5x11extras5 package.
This package is part of QT5 framework, and can be manually installed by:
$sudo apt-get install libqt5x11extras5

The package is probably missing because Ubuntu Touch depends on Mir and the package is related to x11. However, by including this package (very small footprint) it helps with binary compatibility of qt5 bindings for other development tools than the default SDK. 

For example I am writing qt5 application with Lazarus IDE (Object Pascal) and the qt5 binding that I am using link with the libqt5x11extras5 even despite me never needing to call any of the APIs within it (unless maybe in a chroot/proot?). Other development tools may have the same dependency, just so the linking can succeed during the compilation.

### Illustrations
N/A

**Comment by mardy** [comment]
I would rather fix the build system of the application not to link against libqt5x11extras5 when building for UT.

**Comment by dobey** [comment]
Closing this, as really we should work instead to remove as much X11 stuff as possible from the rootfs, and we shouldn't waste space with un-used deps for a very few apps which aren't built to work on Ubuntu Touch with Mir and confinement. As @mardy suggested, it'd be better to fix the build to work without it if one wants to use it in UT as a click package.
