### ISSUE TITLE
qml-module-ubuntu-web is not going to be installed

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-touch-meta#38]
Due to the changes in #37 I'm now not able to install the ubuntu-sdk-libs package in the Clickable amd64 docker container due to this error: `ubuntu-sdk-libs : Depends: qml-module-ubuntu-web but it is not going to be installed`

**Comment by bhdouglass** [comment]
This is also happening in the armhf docker container: `ubuntu-sdk-libs:armhf : Depends: qml-module-ubuntu-web:armhf but it is not going to be installed`

**Comment by mariogrip** [comment]
Humm, A quick fix would be to move it to the touch meta package? @UniversalSuperBox

**Comment by bhdouglass** [comment]
That sounds like a hack, but given that we probably don't want to waste to much time on it, that seems ok to me.

**Comment by UniversalSuperBox** [comment]
Closed by #39

**Comment by bhdouglass** [comment]
Thanks @UniversalSuperBox !
