### ISSUE TITLE
Dependencies issues in clickable armhf/arm64 containers

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-touch-meta#56]
I'm getting some "fun" dependency issues building the clickable armhf and arm64 this month. Nothing has changed on clickable's side and it was building fine last month.

First issue: [1.log](https://github.com/ubports/ubuntu-touch-meta/files/3825718/1.log)

After that I have the Dockerfile install `python3` (which isn't necessary since it's already installed), but that leads to this error: [2.log](https://github.com/ubports/ubuntu-touch-meta/files/3825722/2.log)

After that I add `qml-module-io-thp-pyotherside:armhf` (which probably isn't needed in the armhf container since it's just for building unlike the amd64 one for desktop mode), but that leads to this error: [3.log](https://github.com/ubports/ubuntu-touch-meta/files/3825726/3.log)

So, in the end, I'm unable to build the clickable armhf/arm64 images since both python3 and python3:armhf need to be installed. Any suggestions for how to fix this or work around it are appreciated.

**Comment by bhdouglass** [comment]
Any ideas? this is still happening.

**Comment by bhdouglass** [comment]
Fixed via a nasty hack.

**Comment by mardy** [comment]
Reopening, as I noticed that a similar issue involving `qml-module-io-thp-pyotherside:armhf` happens in the SDK job: https://ci.ubports.com/job/usdk-image-tools/job/master/36/consoleText (and indeed, the last SDK job succeeded in mid-October).

**Comment by mardy** [comment]
A comparison with the [logs of the last successful build](https://ci.ubports.com/job/usdk-image-tools/job/master/35/consoleText) shows that back then `qml-module-io-thp-pyotherside` was not installed.

After more investigations, it appears the the last successful build was done using version `1.433xenial1ubports4` of ubuntu-touch-meta, while the failed one was using `1.433xenial1ubports10`. And indeed, `qml-module-io-thp-pyotherside` [was added](https://github.com/ubports/ubuntu-touch-meta/commit/8c89626c371ad4cb2778a1169169033af1578600) in between of them, in `1.433xenial1ubports5`. I'll make a merge request to propose its removal.

**Comment by Flohack74** [comment]
Well would be interesting why this package was added. Maybe to solve smth else?

**Comment by mardy** [comment]
With https://github.com/ubports/pyotherside-packaging/commit/9aa5c1796bacdbc4f78667918126c7ddb942877a the SDK could be built: https://ci.ubports.com/blue/organizations/jenkins/usdk-image-tools/detail/master/40/pipeline/

I guess that this also means that clickable will be fine. @bhdouglass, can we close this?

**Comment by bhdouglass** [comment]
That seems to have fixed it, thanks!
